export const INDIA_LABEL = "india";

export const INDIA_STATE_TERMS = new Set([
  "andhra pradesh",
  "arunachal pradesh",
  "assam",
  "bihar",
  "chhattisgarh",
  "goa",
  "gujarat",
  "haryana",
  "himachal pradesh",
  "jharkhand",
  "karnataka",
  "kerala",
  "madhya pradesh",
  "maharashtra",
  "manipur",
  "meghalaya",
  "mizoram",
  "nagaland",
  "odisha",
  "orissa",
  "punjab",
  "rajasthan",
  "sikkim",
  "tamil nadu",
  "telangana",
  "tripura",
  "uttar pradesh",
  "uttarakhand",
  "west bengal",
  "andaman and nicobar islands",
  "chandigarh",
  "dadra and nagar haveli and daman and diu",
  "daman and diu",
  "delhi",
  "national capital territory of delhi",
  "jammu and kashmir",
  "ladakh",
  "lakshadweep",
  "puducherry",
]);

export const LOCATION_PREFIX_PATTERN =
  /^(village|vill|post|po|tal|taluka|tehsil|dist|district|near|via)\s+/i;
  
export const INDIA_LOCATION_PARTS = new Set(["india", "in", "ind", "bharat"]);

export const GENERIC_SEARCH_SKILLS = new Set([
  "algorithms",
  "data structures",
  "oop",
  "git",
  "postman",
  "system design",
  "problem solving",
]);

export const COMMON_TECH_SKILLS = [
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "Express",
  "HTML",
  "CSS",
  "Next.js",
  "Angular",
  "Vue",
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "Git",
  "Linux",
  "REST API",
  "GraphQL",
  "Spring Boot",
  "Django",
  "Flask",
  "FastAPI",
  "C#",
  ".NET",
  "PHP",
  "Laravel",
  "Android",
  "iOS",
  "Swift",
  "Kotlin",
  "Machine Learning",
  "AI",
  "Data Analysis",
  "Tableau",
  "Power BI",
  "Excel",
];

export const ENTRY_LEVEL_TITLE_TERMS = [
  "fresher",
  "entry level",
  "entry-level",
  "junior",
  "associate",
  "intern",
  "internship",
  "trainee",
  "apprentice",
  "graduate",
];

export const SENIOR_TITLE_TERMS = [
  "senior",
  "sr",
  "lead",
  "manager",
  "architect",
  "staff",
  "principal",
  "head",
];
